aliases:
    fleeks: cd ~/.local/share/fleek
    g: git
    gbvv: git branch -vv
    gcm: git commit
    gd: git diff
    gdc: git diff --cached
    glg: git log --oneline --decorate --graph
    gs: git status
    cat: bat
    catp: bat -P
    ls: exa
    ll: exa -l
    la: exa -a
    lla: exa -l -a
    lt: exa --tree
    tree: exa --tree
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - ripgrep
    - neovim
    - starship
    - nerdfonts
    - git
    - zsh
    - fzf
    - atuin
    - exa
    - bat
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - starship
    - atuin
    - exa
    - bat
shell: bash
systems:
    - arch: x86_64
      hostname: fedora
      os: linux
      username: aaravchen
track: nixos-unstable
unfree: true
users:
    - email: github@trackit.fe80.email
      name: Mike
      ssh_private_key_file: ~/.ssh/id_ed25519_github
      ssh_public_key_file: ~/.ssh/id_ed25519_github.pub
      username: aaravchen
