aliases:
    fleeks: cd ~/.local/share/fleek
    gcm: git commit
    gs: git status
    ls: ls --color=auto
    vdir: vdir --color=auto
    grep: grep --color=auto
    fgrep: fgrep --color=auto
    egrep: egrep --color=auto
bling: low
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - ripgrep
    - neovim
    - starship
    - nerdfonts
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: fedora
      os: linux
      username: aaravchen
track: nixos-unstable
unfree: true
users:
    - email: github@trackit.fe80.email
      name: Mike
      ssh_private_key_file: ~/.ssh/id_ed25519_github
      ssh_public_key_file: ~/.ssh/id_ed25519_github.pub
      username: aaravchen
