#+TITLE: Writeable Site Emacs Configuration

*WARNING*: Tangle output files are always exclusively next to the fully-resolved path to the org file unless a different output
path is specified in the org file itself. While you can set a hardcoded output path as a =#+PROPERTY:=, you cannot set a dynamic
one this way, it will simply be ignored.

*Be sure each src block to be tangled uses =:tangle (expand-file-name "site-writeable.el" user-emacs-directory)= to specify the output path.*

* Introduction
This file is used to define a tangled configuration that is modifiable without needing to rebuild the nix home-manager config. Intended for
testing changes before they're migrated into the nix config.

This file is loaded last of all the emacs site configuration files so it takes precedence.

*WARNING:* Any =use-package= declarations in this file will only be processed at emacs run-time and will not actually be parsed at nix build-time.

#+begin_src emacs-lisp :tangle (expand-file-name "site-writeable.el" user-emacs-directory)
;; Placeholder so the generated el file isn't blank
#+end_src